//! Clipboard privacy marker policy.
//!
//! These markers are written by password managers and clipboard-aware apps to
//! tell history/sync tools not to retain the current clipboard entry.

#[cfg(any(target_os = "macos", test))]
pub const MACOS_PRIVATE_PASTEBOARD_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

#[cfg(any(target_os = "linux", test))]
pub const LINUX_PASSWORD_MANAGER_HINT_MIME_TYPE: &str = "x-kde-passwordManagerHint";
#[cfg(any(target_os = "linux", test))]
pub const LINUX_PASSWORD_MANAGER_HINT_VALUE: &str = "secret";

#[cfg(any(target_os = "macos", test))]
pub fn is_macos_private_pasteboard_type(pasteboard_type: &str) -> bool {
    MACOS_PRIVATE_PASTEBOARD_TYPES
        .iter()
        .any(|private_type| pasteboard_type.trim().eq_ignore_ascii_case(private_type))
}

#[cfg(any(target_os = "linux", test))]
pub fn is_linux_password_manager_hint_mime_type(mime_type: &str) -> bool {
    normalized_mime_label(mime_type).eq_ignore_ascii_case(&normalized_mime_label(
        LINUX_PASSWORD_MANAGER_HINT_MIME_TYPE,
    ))
}

#[cfg(any(target_os = "linux", test))]
pub fn linux_password_manager_hint_mime_type(mime_types: &[String]) -> Option<&str> {
    mime_types
        .iter()
        .find(|mime_type| is_linux_password_manager_hint_mime_type(mime_type))
        .map(String::as_str)
}

#[cfg(any(target_os = "linux", test))]
pub fn is_linux_password_manager_secret_hint(bytes: &[u8]) -> bool {
    let value = String::from_utf8_lossy(bytes);
    value
        .trim_matches(|ch: char| ch.is_ascii_whitespace() || ch == '\0')
        .eq_ignore_ascii_case(LINUX_PASSWORD_MANAGER_HINT_VALUE)
}

#[cfg(any(target_os = "linux", test))]
fn normalized_mime_label(mime_type: &str) -> String {
    mime_type
        .trim()
        .split(';')
        .next()
        .unwrap_or(mime_type)
        .trim()
        .to_ascii_lowercase()
}

#[cfg(test)]
pub fn has_macos_private_pasteboard_type<'a>(
    pasteboard_types: impl IntoIterator<Item = &'a str>,
) -> bool {
    pasteboard_types
        .into_iter()
        .any(is_macos_private_pasteboard_type)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn macos_private_types_match_known_markers() {
        assert!(is_macos_private_pasteboard_type(
            "org.nspasteboard.ConcealedType"
        ));
        assert!(is_macos_private_pasteboard_type(
            " org.nspasteboard.TransientType "
        ));
        assert!(has_macos_private_pasteboard_type([
            "public.utf8-plain-text",
            "org.nspasteboard.AutoGeneratedType",
        ]));
        assert!(!has_macos_private_pasteboard_type([
            "public.png",
            "public.utf8-plain-text",
        ]));
    }

    #[test]
    fn linux_password_manager_hint_matches_mime_type_and_secret_value() {
        let mime_types = vec![
            "text/plain;charset=utf-8".to_string(),
            "x-kde-passwordManagerHint".to_string(),
        ];

        assert_eq!(
            linux_password_manager_hint_mime_type(&mime_types),
            Some("x-kde-passwordManagerHint")
        );
        assert!(is_linux_password_manager_hint_mime_type(
            " x-kde-passwordmanagerhint "
        ));
        assert!(is_linux_password_manager_secret_hint(b" secret\n"));
        assert!(is_linux_password_manager_secret_hint(b"SECRET\0"));
        assert!(!is_linux_password_manager_secret_hint(b"public"));
    }
}
