[package]
name = "clipper-gym"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["serde", "v5"] }

[dev-dependencies]
serde_json.workspace = true
