//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub blob_path: String,
    #[sea_orm(column_type = "Blob")]
    pub meta_ciphertext: Vec<u8>,
    #[sea_orm(column_type = "Blob")]
    pub meta_nonce: Vec<u8>,
    #[sea_orm(column_type = "Blob")]
    pub blob_nonce: Vec<u8>,
    pub blob_size: i64,
    #[sea_orm(column_type = "Blob")]
    pub sha256_ciphertext: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text")]
    pub source_device_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
