//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "object_revisions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub object_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub revision: i64,
    #[sea_orm(column_type = "Text")]
    pub operation: String,
    #[sea_orm(column_type = "Blob", nullable)]
    pub parent_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Blob")]
    pub meta_ciphertext: Vec<u8>,
    #[sea_orm(column_type = "Blob")]
    pub meta_nonce: Vec<u8>,
    #[sea_orm(column_type = "Blob")]
    pub envelope: Vec<u8>,
    pub source_device_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub stored_at: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_seq: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::SourceDeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Devices,
    #[sea_orm(has_many = "super::object_payloads::Entity")]
    ObjectPayloads,
    #[sea_orm(
        belongs_to = "super::objects::Entity",
        from = "Column::ObjectId",
        to = "super::objects::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Objects,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::object_payloads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ObjectPayloads.def()
    }
}

impl Related<super::objects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Objects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
