//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "object_payloads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub object_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub revision: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub payload_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub ciphertext_path: String,
    #[sea_orm(column_type = "Blob")]
    pub nonce: Vec<u8>,
    pub ciphertext_size: i64,
    #[sea_orm(column_type = "Blob")]
    pub sha256_ciphertext: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::object_revisions::Entity",
        from = "(Column::ObjectId, Column::Revision)",
        to = "(super::object_revisions::Column::ObjectId, super::object_revisions::Column::Revision)",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ObjectRevisions,
}

impl Related<super::object_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ObjectRevisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
