//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "objects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub expires_at: Option<String>,
    pub head_revision: Option<i64>,
    pub published_seq: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    pub collab_doc_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::collab_docs::Entity",
        from = "Column::CollabDocId",
        to = "super::collab_docs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CollabDocs,
    #[sea_orm(has_many = "super::object_revisions::Entity")]
    ObjectRevisions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::collab_docs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollabDocs.def()
    }
}

impl Related<super::object_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ObjectRevisions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
