//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Blob")]
    pub opaque_server_setup: Vec<u8>,
    #[sea_orm(column_type = "Blob")]
    pub opaque_password_file: Vec<u8>,
    #[sea_orm(column_type = "Blob")]
    pub encryption_salt: Vec<u8>,
    #[sea_orm(column_type = "Text", unique)]
    pub access_key_hash: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::access_keys::Entity",
        from = "Column::AccessKeyHash",
        to = "super::access_keys::Column::KeyHash",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    AccessKeys,
    #[sea_orm(has_many = "super::clipboard_items::Entity")]
    ClipboardItems,
    #[sea_orm(has_many = "super::devices::Entity")]
    Devices,
    #[sea_orm(has_many = "super::event_log::Entity")]
    EventLog,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
}

impl Related<super::access_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessKeys.def()
    }
}

impl Related<super::clipboard_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClipboardItems.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::event_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventLog.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
