// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/clipper.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiClipperInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2063723708;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_clipper_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BridgeAppState> crateApiClipperBridgeAppStateDefault();

  Future<BridgeClipboardItem> crateApiClipperBridgeClipboardItemDefault();

  Future<BridgeConnectionStatus> crateApiClipperBridgeConnectionStatusDefault();

  Future<BridgeFileItem> crateApiClipperBridgeFileItemDefault();

  Future<void> crateApiClipperConnectToDaemon();

  Future<String> crateApiClipperCopyToLocal({required String id});

  Future<void> crateApiClipperDeleteFile({required String fileId});

  Future<void> crateApiClipperDownloadFile({
    required String fileId,
    required String targetPath,
  });

  Future<BridgeAppState> crateApiClipperGetState();

  Future<void> crateApiClipperInitApp();

  Future<void> crateApiClipperLogin({
    required String passphrase,
    String? userId,
    required String deviceName,
    required String serverUrl,
  });

  Future<void> crateApiClipperLogout();

  Future<void> crateApiClipperRefresh();

  Future<String> crateApiClipperRegister({
    required String accessKey,
    required String passphrase,
    required String deviceName,
    required String serverUrl,
  });

  Future<void> crateApiClipperSendClipboard({required String text});

  Future<String> crateApiClipperUploadFile({required String filePath});

  Future<void> crateApiClipperWaitForStateChange();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BridgeAppState> crateApiClipperBridgeAppStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_app_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipperBridgeAppStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperBridgeAppStateDefaultConstMeta =>
      const TaskConstMeta(debugName: "bridge_app_state_default", argNames: []);

  @override
  Future<BridgeClipboardItem> crateApiClipperBridgeClipboardItemDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_clipboard_item,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipperBridgeClipboardItemDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperBridgeClipboardItemDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_clipboard_item_default",
        argNames: [],
      );

  @override
  Future<BridgeConnectionStatus>
  crateApiClipperBridgeConnectionStatusDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_connection_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipperBridgeConnectionStatusDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperBridgeConnectionStatusDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_connection_status_default",
        argNames: [],
      );

  @override
  Future<BridgeFileItem> crateApiClipperBridgeFileItemDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_file_item,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipperBridgeFileItemDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperBridgeFileItemDefaultConstMeta =>
      const TaskConstMeta(debugName: "bridge_file_item_default", argNames: []);

  @override
  Future<void> crateApiClipperConnectToDaemon() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperConnectToDaemonConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperConnectToDaemonConstMeta =>
      const TaskConstMeta(debugName: "connect_to_daemon", argNames: []);

  @override
  Future<String> crateApiClipperCopyToLocal({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperCopyToLocalConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperCopyToLocalConstMeta =>
      const TaskConstMeta(debugName: "copy_to_local", argNames: ["id"]);

  @override
  Future<void> crateApiClipperDeleteFile({required String fileId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperDeleteFileConstMeta,
        argValues: [fileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperDeleteFileConstMeta =>
      const TaskConstMeta(debugName: "delete_file", argNames: ["fileId"]);

  @override
  Future<void> crateApiClipperDownloadFile({
    required String fileId,
    required String targetPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fileId, serializer);
          sse_encode_String(targetPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperDownloadFileConstMeta,
        argValues: [fileId, targetPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperDownloadFileConstMeta =>
      const TaskConstMeta(
        debugName: "download_file",
        argNames: ["fileId", "targetPath"],
      );

  @override
  Future<BridgeAppState> crateApiClipperGetState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_app_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipperGetStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperGetStateConstMeta =>
      const TaskConstMeta(debugName: "get_state", argNames: []);

  @override
  Future<void> crateApiClipperInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipperInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiClipperLogin({
    required String passphrase,
    String? userId,
    required String deviceName,
    required String serverUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          sse_encode_opt_String(userId, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_String(serverUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperLoginConstMeta,
        argValues: [passphrase, userId, deviceName, serverUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperLoginConstMeta => const TaskConstMeta(
    debugName: "login",
    argNames: ["passphrase", "userId", "deviceName", "serverUrl"],
  );

  @override
  Future<void> crateApiClipperLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<void> crateApiClipperRefresh() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperRefreshConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperRefreshConstMeta =>
      const TaskConstMeta(debugName: "refresh", argNames: []);

  @override
  Future<String> crateApiClipperRegister({
    required String accessKey,
    required String passphrase,
    required String deviceName,
    required String serverUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accessKey, serializer);
          sse_encode_String(passphrase, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_String(serverUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperRegisterConstMeta,
        argValues: [accessKey, passphrase, deviceName, serverUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperRegisterConstMeta => const TaskConstMeta(
    debugName: "register",
    argNames: ["accessKey", "passphrase", "deviceName", "serverUrl"],
  );

  @override
  Future<void> crateApiClipperSendClipboard({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperSendClipboardConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperSendClipboardConstMeta =>
      const TaskConstMeta(debugName: "send_clipboard", argNames: ["text"]);

  @override
  Future<String> crateApiClipperUploadFile({required String filePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClipperUploadFileConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperUploadFileConstMeta =>
      const TaskConstMeta(debugName: "upload_file", argNames: ["filePath"]);

  @override
  Future<void> crateApiClipperWaitForStateChange() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClipperWaitForStateChangeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClipperWaitForStateChangeConstMeta =>
      const TaskConstMeta(debugName: "wait_for_state_change", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeAppState dco_decode_bridge_app_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BridgeAppState(
      loggedIn: dco_decode_bool(arr[0]),
      userId: dco_decode_opt_String(arr[1]),
      deviceId: dco_decode_opt_String(arr[2]),
      deviceName: dco_decode_opt_String(arr[3]),
      connectionStatus: dco_decode_bridge_connection_status(arr[4]),
      clipboardItems: dco_decode_list_bridge_clipboard_item(arr[5]),
      files: dco_decode_list_bridge_file_item(arr[6]),
      error: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  BridgeClipboardItem dco_decode_bridge_clipboard_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeClipboardItem(
      id: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
      sourceDeviceId: dco_decode_String(arr[3]),
    );
  }

  @protected
  BridgeConnectionStatus dco_decode_bridge_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeConnectionStatus.values[raw as int];
  }

  @protected
  BridgeFileItem dco_decode_bridge_file_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeFileItem(
      id: dco_decode_String(arr[0]),
      filename: dco_decode_String(arr[1]),
      mimeType: dco_decode_String(arr[2]),
      blobSize: dco_decode_i_64(arr[3]),
      createdAt: dco_decode_String(arr[4]),
      sourceDeviceId: dco_decode_String(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<BridgeClipboardItem> dco_decode_list_bridge_clipboard_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_clipboard_item)
        .toList();
  }

  @protected
  List<BridgeFileItem> dco_decode_list_bridge_file_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_file_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeAppState sse_decode_bridge_app_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loggedIn = sse_decode_bool(deserializer);
    var var_userId = sse_decode_opt_String(deserializer);
    var var_deviceId = sse_decode_opt_String(deserializer);
    var var_deviceName = sse_decode_opt_String(deserializer);
    var var_connectionStatus = sse_decode_bridge_connection_status(
      deserializer,
    );
    var var_clipboardItems = sse_decode_list_bridge_clipboard_item(
      deserializer,
    );
    var var_files = sse_decode_list_bridge_file_item(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return BridgeAppState(
      loggedIn: var_loggedIn,
      userId: var_userId,
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      connectionStatus: var_connectionStatus,
      clipboardItems: var_clipboardItems,
      files: var_files,
      error: var_error,
    );
  }

  @protected
  BridgeClipboardItem sse_decode_bridge_clipboard_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_sourceDeviceId = sse_decode_String(deserializer);
    return BridgeClipboardItem(
      id: var_id,
      text: var_text,
      createdAt: var_createdAt,
      sourceDeviceId: var_sourceDeviceId,
    );
  }

  @protected
  BridgeConnectionStatus sse_decode_bridge_connection_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeConnectionStatus.values[inner];
  }

  @protected
  BridgeFileItem sse_decode_bridge_file_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_filename = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_blobSize = sse_decode_i_64(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_sourceDeviceId = sse_decode_String(deserializer);
    return BridgeFileItem(
      id: var_id,
      filename: var_filename,
      mimeType: var_mimeType,
      blobSize: var_blobSize,
      createdAt: var_createdAt,
      sourceDeviceId: var_sourceDeviceId,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<BridgeClipboardItem> sse_decode_list_bridge_clipboard_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeClipboardItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_clipboard_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeFileItem> sse_decode_list_bridge_file_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeFileItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_file_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bridge_app_state(
    BridgeAppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.loggedIn, serializer);
    sse_encode_opt_String(self.userId, serializer);
    sse_encode_opt_String(self.deviceId, serializer);
    sse_encode_opt_String(self.deviceName, serializer);
    sse_encode_bridge_connection_status(self.connectionStatus, serializer);
    sse_encode_list_bridge_clipboard_item(self.clipboardItems, serializer);
    sse_encode_list_bridge_file_item(self.files, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_clipboard_item(
    BridgeClipboardItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.sourceDeviceId, serializer);
  }

  @protected
  void sse_encode_bridge_connection_status(
    BridgeConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_file_item(
    BridgeFileItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.filename, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_i_64(self.blobSize, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.sourceDeviceId, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_bridge_clipboard_item(
    List<BridgeClipboardItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_clipboard_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_file_item(
    List<BridgeFileItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_file_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
