// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_ref`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `from_str`, `from`, `from`, `from`, `from`, `from`, `try_from`

Future<void> connectToDaemon() =>
    RustLib.instance.api.crateApiClipperConnectToDaemon();

Future<void> login({
  required String passphrase,
  required String username,
  required String deviceName,
  required String serverUrl,
}) => RustLib.instance.api.crateApiClipperLogin(
  passphrase: passphrase,
  username: username,
  deviceName: deviceName,
  serverUrl: serverUrl,
);

Future<String> register({
  required String accessKey,
  required String username,
  required String passphrase,
  required String deviceName,
  required String serverUrl,
}) => RustLib.instance.api.crateApiClipperRegister(
  accessKey: accessKey,
  username: username,
  passphrase: passphrase,
  deviceName: deviceName,
  serverUrl: serverUrl,
);

Future<void> logout() => RustLib.instance.api.crateApiClipperLogout();

Future<BridgeAppState> getState() =>
    RustLib.instance.api.crateApiClipperGetState();

Future<void> sendClipboard({required String text}) =>
    RustLib.instance.api.crateApiClipperSendClipboard(text: text);

Future<String> sendClipboardPayload({
  required String mimeType,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiClipperSendClipboardPayload(
  mimeType: mimeType,
  bytes: bytes,
);

Future<String> copyToLocal({required String id}) =>
    RustLib.instance.api.crateApiClipperCopyToLocal(id: id);

Future<BridgeClipboardPayload> clipboardPayload({required String id}) =>
    RustLib.instance.api.crateApiClipperClipboardPayload(id: id);

Future<String> uploadFile({required String filePath}) =>
    RustLib.instance.api.crateApiClipperUploadFile(filePath: filePath);

Future<String> uploadFileBytes({
  required String filename,
  required String mimeType,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiClipperUploadFileBytes(
  filename: filename,
  mimeType: mimeType,
  bytes: bytes,
);

Future<void> downloadFile({
  required String fileId,
  required String targetPath,
}) => RustLib.instance.api.crateApiClipperDownloadFile(
  fileId: fileId,
  targetPath: targetPath,
);

Future<Uint8List> downloadFileBytes({required String fileId}) =>
    RustLib.instance.api.crateApiClipperDownloadFileBytes(fileId: fileId);

Future<void> deleteFile({required String fileId}) =>
    RustLib.instance.api.crateApiClipperDeleteFile(fileId: fileId);

Future<void> refresh() => RustLib.instance.api.crateApiClipperRefresh();

Future<void> waitForStateChange() =>
    RustLib.instance.api.crateApiClipperWaitForStateChange();

class BridgeAppState {
  final bool loggedIn;
  final String? username;
  final String? deviceId;
  final String? deviceName;
  final BridgeConnectionStatus connectionStatus;
  final List<BridgeClipboardItem> clipboardItems;
  final List<BridgeFileItem> files;
  final String? error;

  const BridgeAppState({
    required this.loggedIn,
    this.username,
    this.deviceId,
    this.deviceName,
    required this.connectionStatus,
    required this.clipboardItems,
    required this.files,
    this.error,
  });

  static Future<BridgeAppState> default_() =>
      RustLib.instance.api.crateApiClipperBridgeAppStateDefault();

  @override
  int get hashCode =>
      loggedIn.hashCode ^
      username.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      connectionStatus.hashCode ^
      clipboardItems.hashCode ^
      files.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAppState &&
          runtimeType == other.runtimeType &&
          loggedIn == other.loggedIn &&
          username == other.username &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          connectionStatus == other.connectionStatus &&
          clipboardItems == other.clipboardItems &&
          files == other.files &&
          error == other.error;
}

class BridgeClipboardItem {
  final String id;
  final String text;
  final String mimeType;
  final PlatformInt64 payloadSize;
  final String createdAt;
  final String sourceDeviceId;

  const BridgeClipboardItem({
    required this.id,
    required this.text,
    required this.mimeType,
    required this.payloadSize,
    required this.createdAt,
    required this.sourceDeviceId,
  });

  static Future<BridgeClipboardItem> default_() =>
      RustLib.instance.api.crateApiClipperBridgeClipboardItemDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      mimeType.hashCode ^
      payloadSize.hashCode ^
      createdAt.hashCode ^
      sourceDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeClipboardItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          mimeType == other.mimeType &&
          payloadSize == other.payloadSize &&
          createdAt == other.createdAt &&
          sourceDeviceId == other.sourceDeviceId;
}

class BridgeClipboardPayload {
  final String mimeType;
  final Uint8List bytes;
  final String? text;

  const BridgeClipboardPayload({
    required this.mimeType,
    required this.bytes,
    this.text,
  });

  static Future<BridgeClipboardPayload> default_() =>
      RustLib.instance.api.crateApiClipperBridgeClipboardPayloadDefault();

  @override
  int get hashCode => mimeType.hashCode ^ bytes.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeClipboardPayload &&
          runtimeType == other.runtimeType &&
          mimeType == other.mimeType &&
          bytes == other.bytes &&
          text == other.text;
}

enum BridgeConnectionStatus {
  disconnected,
  connecting,
  connected,
  daemonNotRunning;

  static Future<BridgeConnectionStatus> default_() =>
      RustLib.instance.api.crateApiClipperBridgeConnectionStatusDefault();
}

class BridgeError {
  final String code;
  final String message;

  const BridgeError({required this.code, required this.message});

  static Future<BridgeError> default_() =>
      RustLib.instance.api.crateApiClipperBridgeErrorDefault();

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class BridgeFileItem {
  final String id;
  final String filename;
  final String mimeType;
  final PlatformInt64 blobSize;
  final String createdAt;
  final String sourceDeviceId;

  const BridgeFileItem({
    required this.id,
    required this.filename,
    required this.mimeType,
    required this.blobSize,
    required this.createdAt,
    required this.sourceDeviceId,
  });

  static Future<BridgeFileItem> default_() =>
      RustLib.instance.api.crateApiClipperBridgeFileItemDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      filename.hashCode ^
      mimeType.hashCode ^
      blobSize.hashCode ^
      createdAt.hashCode ^
      sourceDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFileItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          filename == other.filename &&
          mimeType == other.mimeType &&
          blobSize == other.blobSize &&
          createdAt == other.createdAt &&
          sourceDeviceId == other.sourceDeviceId;
}
