// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `from`, `from`, `from`, `from`

Future<void> connectToDaemon() =>
    RustLib.instance.api.crateApiClipperConnectToDaemon();

Future<void> login({
  required String passphrase,
  String? userId,
  required String deviceName,
  required String serverUrl,
}) => RustLib.instance.api.crateApiClipperLogin(
  passphrase: passphrase,
  userId: userId,
  deviceName: deviceName,
  serverUrl: serverUrl,
);

Future<String> register({
  required String accessKey,
  required String passphrase,
  required String deviceName,
  required String serverUrl,
}) => RustLib.instance.api.crateApiClipperRegister(
  accessKey: accessKey,
  passphrase: passphrase,
  deviceName: deviceName,
  serverUrl: serverUrl,
);

Future<void> logout() => RustLib.instance.api.crateApiClipperLogout();

Future<BridgeAppState> getState() =>
    RustLib.instance.api.crateApiClipperGetState();

Future<void> sendClipboard({required String text}) =>
    RustLib.instance.api.crateApiClipperSendClipboard(text: text);

Future<String> copyToLocal({required String id}) =>
    RustLib.instance.api.crateApiClipperCopyToLocal(id: id);

Future<String> uploadFile({required String filePath}) =>
    RustLib.instance.api.crateApiClipperUploadFile(filePath: filePath);

Future<void> downloadFile({
  required String fileId,
  required String targetPath,
}) => RustLib.instance.api.crateApiClipperDownloadFile(
  fileId: fileId,
  targetPath: targetPath,
);

Future<void> deleteFile({required String fileId}) =>
    RustLib.instance.api.crateApiClipperDeleteFile(fileId: fileId);

Future<void> refresh() => RustLib.instance.api.crateApiClipperRefresh();

Future<void> waitForStateChange() =>
    RustLib.instance.api.crateApiClipperWaitForStateChange();

class BridgeAppState {
  final bool loggedIn;
  final String? userId;
  final String? deviceId;
  final String? deviceName;
  final BridgeConnectionStatus connectionStatus;
  final List<BridgeClipboardItem> clipboardItems;
  final List<BridgeFileItem> files;
  final String? error;

  const BridgeAppState({
    required this.loggedIn,
    this.userId,
    this.deviceId,
    this.deviceName,
    required this.connectionStatus,
    required this.clipboardItems,
    required this.files,
    this.error,
  });

  static Future<BridgeAppState> default_() =>
      RustLib.instance.api.crateApiClipperBridgeAppStateDefault();

  @override
  int get hashCode =>
      loggedIn.hashCode ^
      userId.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      connectionStatus.hashCode ^
      clipboardItems.hashCode ^
      files.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAppState &&
          runtimeType == other.runtimeType &&
          loggedIn == other.loggedIn &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          connectionStatus == other.connectionStatus &&
          clipboardItems == other.clipboardItems &&
          files == other.files &&
          error == other.error;
}

class BridgeClipboardItem {
  final String id;
  final String text;
  final String createdAt;
  final String sourceDeviceId;

  const BridgeClipboardItem({
    required this.id,
    required this.text,
    required this.createdAt,
    required this.sourceDeviceId,
  });

  static Future<BridgeClipboardItem> default_() =>
      RustLib.instance.api.crateApiClipperBridgeClipboardItemDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      createdAt.hashCode ^
      sourceDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeClipboardItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          createdAt == other.createdAt &&
          sourceDeviceId == other.sourceDeviceId;
}

enum BridgeConnectionStatus {
  disconnected,
  connecting,
  connected,
  daemonNotRunning;

  static Future<BridgeConnectionStatus> default_() =>
      RustLib.instance.api.crateApiClipperBridgeConnectionStatusDefault();
}

class BridgeFileItem {
  final String id;
  final String filename;
  final String mimeType;
  final PlatformInt64 blobSize;
  final String createdAt;
  final String sourceDeviceId;

  const BridgeFileItem({
    required this.id,
    required this.filename,
    required this.mimeType,
    required this.blobSize,
    required this.createdAt,
    required this.sourceDeviceId,
  });

  static Future<BridgeFileItem> default_() =>
      RustLib.instance.api.crateApiClipperBridgeFileItemDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      filename.hashCode ^
      mimeType.hashCode ^
      blobSize.hashCode ^
      createdAt.hashCode ^
      sourceDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFileItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          filename == other.filename &&
          mimeType == other.mimeType &&
          blobSize == other.blobSize &&
          createdAt == other.createdAt &&
          sourceDeviceId == other.sourceDeviceId;
}
