[package]
name = "clipper-app-types"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[features]
default = []
uniffi = ["dep:uniffi"]

[dependencies]
clipper-gym.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
uniffi = { workspace = true, optional = true }

[dev-dependencies]
postcard.workspace = true
